### PR TITLE
Bugfix

### LINKED ISSUE #200: Unregister command not working
Unregister command does not unregister a registered borrower, instead merely displays "Unknown command".

Expected behavior: Command should unregister the identified borrower.

Steps to reproduce:
* Create a borrower with `register n/test p/91234567 e/test@gmail.com`
* Borrower should have id "K0001"
* Attemt to unregister using command in the image

<hr><sub>[original: weiijiie/ped#2]<br/>
</sub>

### PR DESCRIPTION
**Pull request by linyutinglyt**
closes #200, #223, #224, #232

### CODE REVIEW

**Review by Cronyxx — APPROVED** [review]
LGTM!

File: src/test/java/seedu/address/logic/commands/ServeCommandTest.java [hunk 1]
```diff
@@ -43,4 +45,18 @@ public void execute_borrowerIdNotFound_throwsCommandException() {
...
                 serveCommand.execute(modelManager));
     }
+
+    @Test
+    public void execute_alreadyInServeMode_throwsCommandException() throws CommandException {
+        Model modelManager = new ModelManager();
+        new RegisterCommand(BOB).execute(modelManager);
+        new RegisterCommand(ALICE).execute(modelManager);
+
+        BorrowerId validIdBob = new BorrowerId(VALID_ID_BOB);
```
Comment (hoholyin) [inline src/test/java/seedu/address/logic/commands/ServeCommandTest.java]: I think we should just use `BOB.getBorrowerId()` here instead of using another constant and assuming it will be the same Id as bob

File: src/main/java/seedu/address/model/borrower/Email.java [hunk 2]
```diff
@@ -23,9 +23,10 @@
     private static final String LOCAL_PART_REGEX = "^[\\w" + SPECIAL_CHARACTERS + "]+";
     private static final String DOMAIN_FIRST_CHARACTER_REGEX = "[^\\W_]"; // alphanumeric characters except underscore
     private static final String DOMAIN_MIDDLE_REGEX = "[a-zA-Z0-9.-]*"; // alphanumeric, period and hyphen
-    private static final String DOMAIN_LAST_CHARACTER_REGEX = "[^\\W_]$";
+    private static final String DOMAIN_LAST_CHARACTER_REGEX = "[^\\W_]{2,}$";
```
Comment (hoholyin) [inline src/main/java/seedu/address/model/borrower/Email.java]: Actually I think we should accept 1 character after dot also (unless our ug define valid email to have 2 or more characters after . ) Speaking of which, we need to update UG on what we accept ads valid email address

File: src/test/java/seedu/address/testutil/TypicalBorrowers.java [hunk 3]
```diff
@@ -28,6 +28,8 @@
     public static final BorrowerId ID_FIRST_BORROWER = new BorrowerId("K0001");
     public static final BorrowerId ID_SECOND_BORROWER = new BorrowerId("K0002");
 
+    public static final BorrowerId ID_ALICE = new BorrowerId("K0001");
```
Comment (hoholyin) [inline src/test/java/seedu/address/testutil/TypicalBorrowers.java]: Can we make us of the already declared `ID_FIRST_BORROWER` instead of creating a new `ID_ALICE`? Just a suggestion

File: src/main/java/seedu/address/model/borrower/Email.java [hunk 4]
```diff
@@ -23,9 +23,10 @@
...
     private static final String VALIDATION_REGEX = LOCAL_PART_REGEX + "@"
```
Comment (hoholyin) [inline src/main/java/seedu/address/model/borrower/Email.java:27]: Beautiful regex 💯

**Review by hoholyin — COMMENTED** [review]
Just a few comments but generally ok 👍

File: src/test/java/seedu/address/logic/commands/ServeCommandTest.java (hunk 1 above)
Comment (linyutinglyt) [reply src/test/java/seedu/address/logic/commands/ServeCommandTest.java]: Good idea!

File: src/main/java/seedu/address/model/borrower/Email.java (hunk 2 above)
Comment (linyutinglyt) [reply src/main/java/seedu/address/model/borrower/Email.java]: Yup true.

File: src/test/java/seedu/address/testutil/TypicalBorrowers.java (hunk 3 above)
Comment (linyutinglyt) [reply src/test/java/seedu/address/testutil/TypicalBorrowers.java]: > Can we make us of the already declared `ID_FIRST_BORROWER` instead of creating a new `ID_ALICE`? Just a suggestion

Was going to use alice's ID and I thought using the name ID_ALICE feels clearer. But going to remove this and use getBorrowerId() instead anyway!

File: src/main/java/seedu/address/model/borrower/Email.java (hunk 4 above)
Comment (linyutinglyt) [reply src/main/java/seedu/address/model/borrower/Email.java:27]: > Beautiful regex 💯

Actually spent some time understanding and getting my brain fried
